name: Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    # Below borrowed from https://github.com/actions/upload-release-asset
    - name: Build project
      run: |
        mkdir dt-maarifa
        cp -r disciple-tools-maarifa.php admin hooks post-type site-link tile languages version-control.json LICENSE dt-maarifa/
        zip -r dt-maarifa.zip dt-maarifa
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: ./dt-maarifa.zip
        generate_release_notes: true
